name: Test Dynamic Matrices
on: [push]
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Using gaia version ${{ matrix.gaia_version}}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate start versions
        id: generate-start
        run: |
          src/generate_version.matrix.py
      - run: echo "ğŸ This job's status is ${{ job.status }}."
    outputs:
      start_versions: ${{ steps.generate_start.outputs.generate_matrix }}
  use-matrix:
    runs-on: ubuntu-latest
    needs: generate-matrix
    steps:
      - run: echo ${{ needs.generate_matrix.outputs.start_versions }}
    # strategy:
      # matrix:
        # gaia_version: ${{ needs.generate_matrix.outputs.start_versions }}
