name: Test Gaia Playbook
on: [push]
jobs:
  build:
    strategy:
      matrix:
        gaia_version: ['v7.0.0','v7.0.1']
  steps:
    - name: Print matrix value
      run: echo "Using gaia version ${{ matrix.gaia_version }}"
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Check out repository code
    #     uses: actions/checkout@v3
    #   - name: Set up Python
    #     uses: actions/setup-python@v3
    #     with:
    #       python-version: '3.10'
    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt
    #   - name: Run playbook
    #     run: |
    #       ansible-playbook src/sandbox.yml -i src/test-inventory.yml 


      # - name: Run playbook
      #   run: |
      #     ansible-playbook gaia.yml -i src/local-net.yml
      # - name: Get gaia status
      #   run: |
      #     sleep 30
      #     ansible-playbook src/gaia-test.yml
      # - run: echo "ğŸ This job's status is ${{ job.status }}."

# name: Explore GitHub Actions
# on: [push]
# jobs:
#   Run-Ansible-Playbook:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: '3.10'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Run playbook
#         run: |
#           ansible-playbook gaia.yml -i src/theta.yml
#       - run: echo "ğŸ This job's status is ${{ job.status }}."


# name: GitHub Actions Demo
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."
